version: "3.8"
services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    restart: always
    ports: 
      - "5432:5432"
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: postgres
        # GOOSE_DRIVER: postgres
        # GOOSE_DBSTRING: "host=postgres user=postgres dbname=postgres sslmode=disable password=postgres"
  api:
    container_name: api
    restart: on-failure
    build: .
    ports:
    - "4040:4040"


